export const supabaseUrl = "https://jmdojtzkjpyvzsfmpyms.supabase.co";
export const supabaseAnonKey =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImptZG9qdHpranB5dnpzZm1weW1zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njc5OTI4MDUsImV4cCI6MjA4MzU2ODgwNX0.VDl6zgn_ulHf6H-sGw1tS1zJqXiqsZEm1M7J9Ug3Vtw";
